project:
  type: website
  output-dir: report

website:
  title: "农业面源污染可重复性研究"
  description: "K-Means聚类与多元回归分析"
  output-file: index
  search:
    location: navbar
    type: header

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
